site_name: Introduction to Linux
site_url: https://hpc2n.github.io/intro-linux/
site_description: Material for the course Introduction to Linux
site_dir: site.build
theme:
  name: readthedocs
  locale: en
  logo: images/hpc2n-blue-text-intro-linux.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  tabs: true
  language: en
extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Home: index.md
  - Introduction: intro.md
    #  - Linux terminology: linux.md
  - The command line (CLI): cli.md
  - The File System: filesystem.md
  - Pipes and filters: pipesfilters.md
  - Editors: editors.md
  - Patterns and scripting: patterns.md
  - Data Handling: data.md
  - Hints and tricks: hints.md
  - Summary: summary.md
  - Extras: 
    - Install tree: tree.md
    - Linux system overview: connections.md
    - Linux terminology: linux-terms.md
    - More commands: more-commands.md
    - Linux cheat sheet: cheat.md
plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "__"
